/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationAnalyticsRouteImport } from './routes/organization.analytics'
import { Route as OrganizationResourcesIndexRouteImport } from './routes/organization.resources.index'
import { Route as OrganizationResourcesNewRouteImport } from './routes/organization.resources.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationAnalyticsRoute = OrganizationAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationResourcesIndexRoute =
  OrganizationResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationResourcesNewRoute =
  OrganizationResourcesNewRouteImport.update({
    id: '/resources/new',
    path: '/resources/new',
    getParentRoute: () => OrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/matches': typeof MatchesRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/analytics': typeof OrganizationAnalyticsRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/resources/new': typeof OrganizationResourcesNewRoute
  '/organization/resources/': typeof OrganizationResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/matches': typeof MatchesRoute
  '/organization/analytics': typeof OrganizationAnalyticsRoute
  '/organization': typeof OrganizationIndexRoute
  '/organization/resources/new': typeof OrganizationResourcesNewRoute
  '/organization/resources': typeof OrganizationResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/matches': typeof MatchesRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/analytics': typeof OrganizationAnalyticsRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/resources/new': typeof OrganizationResourcesNewRoute
  '/organization/resources/': typeof OrganizationResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/matches'
    | '/organization'
    | '/organization/analytics'
    | '/organization/'
    | '/organization/resources/new'
    | '/organization/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/matches'
    | '/organization/analytics'
    | '/organization'
    | '/organization/resources/new'
    | '/organization/resources'
  id:
    | '__root__'
    | '/'
    | '/get-started'
    | '/matches'
    | '/organization'
    | '/organization/analytics'
    | '/organization/'
    | '/organization/resources/new'
    | '/organization/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  MatchesRoute: typeof MatchesRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/analytics': {
      id: '/organization/analytics'
      path: '/analytics'
      fullPath: '/organization/analytics'
      preLoaderRoute: typeof OrganizationAnalyticsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/resources/': {
      id: '/organization/resources/'
      path: '/resources'
      fullPath: '/organization/resources/'
      preLoaderRoute: typeof OrganizationResourcesIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/resources/new': {
      id: '/organization/resources/new'
      path: '/resources/new'
      fullPath: '/organization/resources/new'
      preLoaderRoute: typeof OrganizationResourcesNewRouteImport
      parentRoute: typeof OrganizationRoute
    }
  }
}

interface OrganizationRouteChildren {
  OrganizationAnalyticsRoute: typeof OrganizationAnalyticsRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  OrganizationResourcesNewRoute: typeof OrganizationResourcesNewRoute
  OrganizationResourcesIndexRoute: typeof OrganizationResourcesIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationAnalyticsRoute: OrganizationAnalyticsRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  OrganizationResourcesNewRoute: OrganizationResourcesNewRoute,
  OrganizationResourcesIndexRoute: OrganizationResourcesIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  MatchesRoute: MatchesRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
